Algoritmo "funcoes_matematicas"
Var
   A: real
Inicio
   A <- Abs(-50)
   Escreval("O valor absoluto -50 e", A)
   
   A <- Exp(9, 5)
   Escreval("9 elevado a quinta potencia e", A)
   
   A <- RaizQ(81)
   Escreval("A raiz quadrada de 81 e", A)
   
   A <- Int(RaizQ(90))
   Escreval("A parte inteira da raiz quadrada de 90 e", A)
   
   A <- GraupRad(90)
   Escreval("Conversao de grau para radiano de 90 e", A)
   
   A <- Sen(GraupRad(90))
   Escreval("Seno de 90 e", A)
   
Fimalgoritmo